project_name: ksctl

builds:
  - binary: ksctl
    main: ./cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: -w -s -X github.com/kubesimplify/ksctl/selfupdate.BuildDate={{.Date}} -X github.com/kubesimplify/ksctl/selfupdate.GitSummary={{.Version}}
    env:
      - CGO_ENABLED=0

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.cert'
    args:
      - sign-blob
      - '--output-certificate=${certificate}' 
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: all
    output: true
