project_name: ksctl

builds:
  - binary: ksctl
    main: ./cli
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "github.com/kubesimplify/ksctl/cli/cmd.BuildDate={{.Env.DATE}}"
      - -s -w -X "github.com/kubesimplify/ksctl/cli/cmd.Version={{.Env.VERSION}}"
    env:
      - CGO_ENABLED=0

signs:
  - cmd: cosign
    certificate: '${artifact}.cert'
    args:
      - sign-blob
      - '--output-certificate=${certificate}' 
      - '--output-signature=${signature}'
      - '${artifact}'
      - --yes
    artifacts: all
    output: true
