pipeline {
    agent any

    stages {

        stage('Local Managed') {
            steps{
                sh '''
                    #!/bin/bash

					cd test/e2e

					/usr/local/go/bin/go run . -op create -file local/create.json

                    /usr/local/go/bin/go run . -op get -file local/get.json

                '''
            }
        }

        stage('Test Switching') {
            steps {
                sh '''
                    #!/bin/bash
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/kubeconfig"

					cd test/e2e

                    echo "@@@ Managed Cluster @@@"
					/usr/local/go/bin/go run . -op switch -file local/switch.json

                    tree "/var/lib/jenkins/.ksctl/state"

                    jq -r . /var/lib/jenkins/.ksctl/state/local/managed/test-e2e-local\\ LOCAL/state.json

                    kubectl get nodes -owide
                '''
            }
        }
    }

    post {
        always {
            sh '''
                #!/bin/bash

				cd test/e2e
				/usr/local/go/bin/go run . -op delete -file local/delete.json
            '''
        }
    }
}
