pipeline {
    agent any

    stages {

        stage('Local Managed') {
            steps{
                sh '''
                    #!/bin/bash

					export PATH="$PATH:/usr/local/go/bin"
					cd test/e2e/local
					go run . -op create -file input.json

                    ksctl get
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/local/managed/test-e2e-local/kubeconfig"

                    kubectl get nodes -owide
                '''
            }
        }

        stage('Test Switching') {
            steps {
                sh '''
                    #!/bin/bash

					export PATH="$PATH:/usr/local/go/bin"
					cd test/e2e/local
					go run . -op switch -file input.json
                '''
            }
        }
    }

    post {
        always {
            sh '''
                #!/bin/bash

                export PATH="$PATH:/usr/local/go/bin"
				cd test/e2e/local
				go run . -op delete -file input.json
            '''
        }
    }
}
