pipeline {
    agent any
    environment {
        CIVO_TOKEN = credentials("civo_token")
    }

    stages {
        stage('create managed') {
            steps{
                sh '''
                    #!/bin/bash

                    ksctl create civo -n test-e2e-civo -r LON1 --approve


                    ksctl get
                    tree "/var/lib/jenkins/.ksctl/config"

                    cd /var/lib/jenkins/.ksctl/config/civo/managed/test-e2e-civo\\ LON1

                    jq . cloud-state.json

                    sleep 5s
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/civo/managed/test-e2e-civo LON1/kubeconfig"

                    kubectl get nodes -owide
                '''
            }
        }

        stage('ha cluster') {
            steps {
                sh '''
                    #!/bin/bash
                    ksctl create ha-civo -n test-e2e-ha-civo -r FRA1 --approve

                    ksctl get
                    tree "/var/lib/jenkins/.ksctl/config"

                    cd /var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo\\ FRA1

                    jq . cloud-state.json
                    jq . k8s-state.json

                    sleep 5s
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo FRA1/kubeconfig"

                    kubectl get nodes -owide
                '''
            }
        }

        stage ('switch') {
            steps {
                sh '''
                    #!/bin/bash
                    ksctl switch -p civo -n test-e2e-civo -r LON1
                    ksctl switch -p ha-civo -n test-e2e-ha-civo -r FRA1
                '''
            }
        }

        stage('ha-del-nodes') {
            steps {
                sh '''
                    #!/bin/bash
                    sleep 30s
                    ksctl delete ha-civo delete-nodes -n test-e2e-ha-civo -r FRA1 --noWP 0 --approve

                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo FRA1/kubeconfig"
                    kubectl get nodes -owide
                    cd /var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo\\ FRA1

                    jq . cloud-state.json
                    jq . k8s-state.json
                '''
            }
        }

        stage('ha-add-nodes') {
            steps {
                sh '''
                    #!/bin/bash
                    sleep 1m
                    ksctl create ha-civo add-nodes -n test-e2e-ha-civo -r FRA1 --noWP 1 --approve

                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo FRA1/kubeconfig"
                    kubectl get nodes -owide
                    cd /var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo\\ FRA1

                    jq . cloud-state.json
                    jq . k8s-state.json
                '''
            }
        }
    }

    post {
        always {
            sh '''
                #!/bin/bash
                ksctl delete civo -n test-e2e-civo -r LON1 --approve -v
                ksctl delete ha-civo -n test-e2e-ha-civo -r FRA1 --approve -v
            '''
        }
    }
}
