name: Feature Proposal
title: "[Feature]: "
description: "🌟 Propose a new feature to enhance our project"
labels: ["kind/feature", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        # 🌟 New Feature Proposal

        Thank you for proposing a new feature! Your ideas help make our project better.

        > 💡 Before submitting, please check if a similar feature has been proposed.

        Let's explore your innovative idea together! 🚀

  - type: input
    id: feature-name
    attributes:
      label: "✨ Feature Name"
      description: "What would you like to call this feature?"
      placeholder: "Example: Automated Cluster Backup"
    validations:
      required: true

  - type: input
    id: why
    attributes:
      label: "🎯 Purpose"
      description: "What problem does this feature solve?"
      placeholder: "Example: Users need a way to automatically backup their clusters"
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: "📝 Feature Description"
      description: "Describe how your feature would work"
      placeholder: |
        Please include:
        - Detailed description of the feature
        - How users will interact with it
        - Any technical requirements
        - Expected behavior

        You can use code examples:
        ```bash
        # Example usage
        ksctl backup create --schedule="0 0 * * *"
        ```
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: "🎁 Benefits"
      description: "How will this feature improve the project?"
      placeholder: |
        Examples of benefits:
        - Improves user productivity by...
        - Reduces operational complexity by...
        - Enhances security through...
    validations:
      required: true

  - type: textarea
    id: potential-drawbacks
    attributes:
      label: "⚖️ Potential Drawbacks"
      description: "What are the potential challenges or trade-offs?"
      placeholder: |
        Consider:
        - Performance implications
        - Maintenance overhead
        - Complexity added
        - Resource requirements
    validations:
      required: false

  - type: textarea
    id: alternatives-considered
    attributes:
      label: "🔄 Alternatives Considered"
      description: "What other approaches have you considered?"
      placeholder: |
        For each alternative:
        - Description of the approach
        - Why it wasn't chosen
        - Comparison with proposed solution
    validations:
      required: false

  - type: checkboxes
    id: impact-areas
    attributes:
      label: "🎯 Impact Areas"
      description: "Which components will be affected by this feature?"
      options:
        - label: "🖥️ CLI - Command line interface"
        - label: "🎨 UI - User interface"
        - label: "📚 Documentation"
        - label: "⚙️ Core Features"
        - label: "🔌 External Integrations"
        - label: "🧪 Testing Infrastructure"

  - type: textarea
    id: implementation-details
    attributes:
      label: "🛠️ Implementation Details"
      description: "Any technical details about the implementation?"
      placeholder: |
        Include if you have thoughts on:
        - Technical architecture
        - Required dependencies
        - Integration points
        - Migration considerations
    validations:
      required: false

  - type: checkboxes
    id: agreement
    attributes:
      label: "📋 Agreements"
      description: |
        Before submitting, please confirm:
      options:
        - label: "🤝 I agree to follow the [Contribution Guidelines](https://docs.ksctl.com/docs/contribution-guidelines/)"
          required: true
        - label: "🔍 I have searched for similar feature requests"
          required: true
        - label: "💬 I will participate in the discussion about this feature"
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        ### 🙏 Thank you for your contribution!

        Our maintainers will review your proposal and provide feedback soon.

        > 💪 Want to implement this feature? Let us know in the comments!
