pipeline {
    agent any
    stages {

        stage('Setup e2e test files') {
            when {
                anyOf {
                    changeset "go.mod"
                    changeset "go.sum"
                    changeset "internal/**"
                    changeset "pkg/**"
                    changeset "test/e2e/**"
                    changeset "test/e2e-jenkins/**"
                }
            }
            steps{
                sh '''
                #!/bin/bash
                /usr/local/go/bin/go version

                echo "SETUP DONE"
                '''
            }
        }


        stage('Trigger Other Pipelines') {
            when {
                anyOf {
                    changeset "go.mod"
                    changeset "go.sum"
                    changeset "internal/**"
                    changeset "pkg/**"
                    changeset "test/e2e-jenkins/**"
                    changeset "test/e2e/**"
                }
            }
            failFast true
            parallel {
                stage('cloud provider') {
                    stages {
                        stage('trigger local') {
                            when {
                                anyOf {
                                    changeset "go.mod"
                                    changeset "go.sum"
                                    changeset "test/e2e-jenkins/**"
                                    changeset "test/e2e/**"
                                    changeset "internal/cloudproviders/local/**"
                                    changeset "pkg/helpers/**"
                                    changeset "pkg/resources/**"
									changeset "pkg/controllers/**"
                                }
                            }
                            steps {
                                build job: 'ksctl (local)', parameters: [string(name: 'GIT_BRANCH', value: "main")]
                            }
                        }
                        stage('trigger civo') {
                            when {
                                anyOf {
                                    changeset "go.mod"
                                    changeset "go.sum"
                                    changeset "test/e2e-jenkins/**"
                                    changeset "test/e2e/**"
                                    changeset "internal/cloudproviders/civo/**"
                                    changeset "pkg/helpers/**"
									changeset "pkg/controllers/**"
                                    changeset "pkg/resources/**"
                                }
                            }
                            steps {
                                build job: 'ksctl (civo)', parameters: [string(name: 'GIT_BRANCH', value: "main")]
                            }
                        }
                        stage('trigger azure') {
                            when {
                                anyOf {
                                    changeset "go.mod"
                                    changeset "go.sum"
                                    changeset "test/e2e/**"
                                    changeset "test/e2e-jenkins/**"
                                    changeset "internal/cloudproviders/azure/**"
                                    changeset "pkg/helpers/**"
                                    changeset "pkg/resources/**"
									changeset "pkg/controllers/**"
                                }
                            }
                            steps {
                                build job: 'ksctl (azure)', parameters: [string(name: 'GIT_BRANCH', value: "main")]
                            }
                        }
                    }
                }
            }
        }
    }
    post {
		always {
			emailext body: '''
                [KSCTL-e2e Testing on main branch]
                $DEFAULT_CONTENT
                ''', mimeType: 'text/html', subject: 'NO-REPLY ksctl-bot: $DEFAULT_SUBJECT', to: 'dipankar@dipankar-das.com'

			sh '''
                #!/bin/bash
                # Setup the configurations dir
                rm -rf ${HOME}/.ksctl
			'''
		}
	}
}
