swagger: "2.0"
info:
    title: ksctl http server
    description: ksctl server for http based usage
    version: ""
host: 0.0.0.0:8080
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /healthz:
        get:
            tags:
                - httpserver
            summary: get health httpserver
            operationId: httpserver#get health
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HttpserverGetHealthResponseBody'
            schemes:
                - http
    /openapi3.json:
        get:
            tags:
                - httpserver
            summary: Download ./gen/http/openapi3.json
            operationId: httpserver#/openapi3.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /swaggerui/{path}:
        get:
            tags:
                - httpserver
            summary: Download ./swaggerui
            operationId: httpserver#/swaggerui/{*path}
            parameters:
                - name: path
                  in: path
                  description: Relative file path
                  required: true
                  type: string
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
                "404":
                    description: File not found
                    schema:
                        $ref: '#/definitions/Error'
            schemes:
                - http
definitions:
    Error:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Error response result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    HttpserverGetHealthResponseBody:
        title: HttpserverGetHealthResponseBody
        type: object
        properties:
            msg:
                type: string
                description: message
                example: Nobis est illum similique illum ducimus sit.
        example:
            msg: Assumenda cumque et.
