pipeline {
    agent any
    environment {
        CIVO_TOKEN = credentials("civo_token")
    }

    stages {
        stage('create managed') {
            steps{
                sh '''
                    #!/bin/bash

                    cd test/e2e

                    /usr/local/go/bin/go run . -op create -file civo/create.json


                    /usr/local/go/bin/go run . -op get -file civo/get.json

                    tree "/var/lib/jenkins/.ksctl/config"

                    cd /var/lib/jenkins/.ksctl/config/civo/managed/test-e2e-civo\\ LON1

                    jq . cloud-state.json

                    sleep 5s
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/civo/managed/test-e2e-civo LON1/kubeconfig"

                    kubectl get nodes -owide
                '''
            }
        }

        stage('ha cluster') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op create -file civo/create-ha.json

                    /usr/local/go/bin/go run . -op get -file civo/get.json

                    tree "/var/lib/jenkins/.ksctl/config"

                    cd /var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo\\ FRA1

                    jq . cloud-state.json
                    jq . k8s-state.json

                    sleep 5s
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo FRA1/kubeconfig"

                    kubectl get nodes -owide
                '''
            }
        }

        stage ('switch') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op switch -file civo/switch.json
                    /usr/local/go/bin/go run . -op switch -file civo/switch-ha.json
                '''
            }
        }

        stage('ha-del-nodes') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    sleep 30s
                    /usr/local/go/bin/go run . -op scaledown -file civo/scaledown-ha.json

                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo FRA1/kubeconfig"
                    kubectl get nodes -owide
                    cd /var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo\\ FRA1

                    jq . cloud-state.json
                    jq . k8s-state.json
                '''
            }
        }

        stage('ha-add-nodes') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    sleep 1m
                    /usr/local/go/bin/go run . -op scaleup -file civo/scaleup-ha.json

                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo FRA1/kubeconfig"
                    kubectl get nodes -owide
                    cd /var/lib/jenkins/.ksctl/config/civo/ha/test-e2e-ha-civo\\ FRA1

                    jq . cloud-state.json
                    jq . k8s-state.json
                '''
            }
        }
    }

    post {
        always {
            sh '''
                #!/bin/bash
                cd test/e2e

                /usr/local/go/bin/go run . -op delete -file civo/delete.json
                /usr/local/go/bin/go run . -op delete -file civo/delete-ha.json
            '''
        }
    }
}
