pipeline {
    agent any
    environment {
        CIVO_TOKEN = credentials("civo_token")
    }

    stages {
        stage('create managed') {
            steps{
                sh '''
                    #!/bin/bash

                    cd test/e2e

                    /usr/local/go/bin/go run . -op create -file civo/create.json


                    /usr/local/go/bin/go run . -op get -file civo/get.json
                '''
            }
        }

        stage('create ha cluster k3s') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op create -file civo/create-ha.json

                    /usr/local/go/bin/go run . -op get -file civo/get.json
                '''
            }
        }

        stage('create ha cluster kubeadm') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op create -file civo/create-ha-kubeadm.json

                    /usr/local/go/bin/go run . -op get -file civo/get.json
                '''
            }
        }

        stage ('switch') {
            steps {
                sh '''
                    #!/bin/bash
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/kubeconfig"

                    cd test/e2e

                    echo "@@@ Managed Cluster @@@"
                    /usr/local/go/bin/go run . -op switch -file civo/switch.json

                    tree "/var/lib/jenkins/.ksctl/state"

                    jq -r . /var/lib/jenkins/.ksctl/state/civo/managed/test-e2e-civo\\ LON1/state.json

                    sleep 5s

                    kubectl get nodes -owide

                    echo "@@@ HA Cluster (K3s) @@@"
                    /usr/local/go/bin/go run . -op switch -file civo/switch-ha.json

                    tree "/var/lib/jenkins/.ksctl/state"

                    jq -r . /var/lib/jenkins/.ksctl/state/civo/ha/test-e2e-ha-civo\\ FRA1/state.json

                    sleep 5s

                    kubectl get nodes -owide

                    echo "@@@ HA Cluster (Kubeadm) @@@"
                    /usr/local/go/bin/go run . -op switch -file civo/switch-ha-kubeadm.json

                    tree "/var/lib/jenkins/.ksctl/state"

                    jq -r . /var/lib/jenkins/.ksctl/state/civo/ha/test-e2e-kubeadm-ha-civo\\ FRA1/state.json

                    sleep 5s

                    kubectl get nodes -owide
                '''
            }
        }


        stage('ha-del-nodes kubeadm') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op switch -file civo/switch-ha-kubeadm.json
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/kubeconfig"

                    sleep 30s
                    /usr/local/go/bin/go run . -op scaledown -file civo/scaledown-ha-kubeadm.json

                    kubectl get nodes -owide
                    jq -r . /var/lib/jenkins/.ksctl/state/civo/ha/test-e2e-kubeadm-ha-civo\\ FRA1/state.json

                '''
            }
        }

        stage('ha-add-nodes kubeadm') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op switch -file civo/switch-ha-kubeadm.json
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/kubeconfig"

                    sleep 1m
                    /usr/local/go/bin/go run . -op scaleup -file civo/scaleup-ha-kubeadm.json

                    kubectl get nodes -owide
                    jq -r . /var/lib/jenkins/.ksctl/state/civo/ha/test-e2e-kubeadm-ha-civo\\ FRA1/state.json

                '''
            }
        }

        stage('ha-del-nodes k3s') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op switch -file civo/switch-ha.json
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/kubeconfig"

                    sleep 30s
                    /usr/local/go/bin/go run . -op scaledown -file civo/scaledown-ha.json

                    kubectl get nodes -owide
                    jq -r . /var/lib/jenkins/.ksctl/state/civo/ha/test-e2e-ha-civo\\ FRA1/state.json

                '''
            }
        }

        stage('ha-add-nodes k3s') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op switch -file civo/switch-ha.json
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/kubeconfig"

                    sleep 1m
                    /usr/local/go/bin/go run . -op scaleup -file civo/scaleup-ha.json

                    kubectl get nodes -owide
                    jq -r . /var/lib/jenkins/.ksctl/state/civo/ha/test-e2e-ha-civo\\ FRA1/state.json

                '''
            }
        }
    }

    post {
        always {
            sh '''
                #!/bin/bash
                cd test/e2e

                /usr/local/go/bin/go run . -op delete -file civo/delete.json
                /usr/local/go/bin/go run . -op delete -file civo/delete-ha.json
                /usr/local/go/bin/go run . -op delete -file civo/delete-ha-kubeadm.json
            '''
        }
    }
}
