pipeline {
    agent any

    stages {

        stage('Local Managed') {
            steps{
                sh '''
                    #!/bin/bash

                    ksctl create local -n test-e2e-local --approve -v

                    ksctl get
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/local/managed/test-e2e-local/kubeconfig"

                    kubectl get nodes -owide
                '''
            }
        }

        stage('Test Switching') {
            steps {
                sh '''
                    #!/bin/bash
                    ksctl switch -p local -n test-e2e-local
                '''
            }
        }
    }

    post {
        always {
            sh '''
                #!/bin/bash
                ksctl delete local -n test-e2e-local --approve -v || exit 0
            '''
        }
    }
}
