pipeline {
    agent any
    environment {
        AZURE_CLIENT_ID = credentials("client_id")
        AZURE_CLIENT_SECRET = credentials("client_secret")
        AZURE_SUBSCRIPTION_ID = credentials("subscriptionid")
        AZURE_TENANT_ID = credentials("tenantid")
    }

    stages {

        stage('create managed') {
            steps{
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op create -file azure/create.json

                    /usr/local/go/bin/go run . -op get -file azure/get.json
                '''
            }
        }

        stage('ha cluster') {
            steps {
                sh '''
                    #!/bin/bash
                    cd test/e2e

                    /usr/local/go/bin/go run . -op create -file azure/create-ha.json

                    /usr/local/go/bin/go run . -op get -file azure/get.json
                '''
            }
        }

        stage('switch') {
            steps {
                sh '''
                    #!/bin/bash
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/kubeconfig"

                    cd test/e2e

                    echo "@@@ Managed Cluster @@@"

                    /usr/local/go/bin/go run . -op switch -file azure/switch.json

                    tree "/var/lib/jenkins/.ksctl/state"

                    cd /var/lib/jenkins/.ksctl/state/azure/managed/test-e2e-azure\\ eastus

                    jq . state.json

                    sleep 5s

                    kubectl get nodes -owide

                    echo "@@@ HA Cluster @@@"

                    /usr/local/go/bin/go run . -op switch -file azure/switch-ha.json

                    tree "/var/lib/jenkins/.ksctl/state"

                    cd /var/lib/jenkins/.ksctl/state/azure/ha/test-e2e-ha-azure\\ eastus2

                    jq . state.json
                    sleep 5s

                    kubectl get nodes -owide
                '''
            }
        }

        stage('ha-del-nodes') {
            steps {
                sh '''
                    #!/bin/bash
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/kubeconfig"

                    cd test/e2e

                    sleep 15s

                    /usr/local/go/bin/go run . -op scaledown -file azure/scaledown-ha.json

                    kubectl get nodes -owide

                    cd /var/lib/jenkins/.ksctl/state/azure/ha/test-e2e-ha-azure\\ eastus2

                    jq . state.json

                '''
            }
        }

        stage('ha-add-nodes') {
            steps {
                sh '''
                    #!/bin/bash
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/kubeconfig"

                    cd test/e2e

                    sleep 1m
                    /usr/local/go/bin/go run . -op scaleup -file azure/scaleup-ha.json

                    kubectl get nodes -owide

                    cd /var/lib/jenkins/.ksctl/state/azure/ha/test-e2e-ha-azure\\ eastus2

                    jq . state.json

                '''
            }
        }
    }

    post {
        always {
            sh '''
                #!/bin/bash
                cd test/e2e

                /usr/local/go/bin/go run . -op delete -file azure/delete.json
                /usr/local/go/bin/go run . -op delete -file azure/delete-ha.json
            '''
        }
    }
}
