pipeline {
    agent any
    environment {
        AZURE_CLIENT_ID = credentials("client_id")
        AZURE_CLIENT_SECRET = credentials("client_secret")
        AZURE_SUBSCRIPTION_ID = credentials("subscriptionid")
        AZURE_TENANT_ID = credentials("tenantid")
    }

    stages {

        stage('create managed') {
            steps{
                sh '''
                    #!/bin/bash

                    ksctl create azure -n test-e2e-azure -r eastus --approve

                    ksctl get
                    tree "/var/lib/jenkins/.ksctl/config"

                    cd /var/lib/jenkins/.ksctl/config/azure/managed/test-e2e-azure\\ test-e2e-azure-ksctl-managed-resgrp\\ eastus

                    jq . cloud-state.json

                    sleep 5s
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/azure/managed/test-e2e-azure test-e2e-azure-ksctl-managed-resgrp eastus/kubeconfig"

                    kubectl get nodes -owide
                '''
            }
        }

        stage('ha cluster') {
            steps {
                sh '''
                    #!/bin/bash
                    ksctl create ha-azure -n test-e2e-ha-azure -r eastus2 --approve

                    ksctl get
                    tree "/var/lib/jenkins/.ksctl/config"

                    cd /var/lib/jenkins/.ksctl/config/azure/ha/test-e2e-ha-azure\\ test-e2e-ha-azure-ksctl-ha-resgrp\\ eastus2

                    jq . cloud-state.json
                    jq . k8s-state.json
                    sleep 5s
                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/azure/ha/test-e2e-ha-azure test-e2e-ha-azure-ksctl-ha-resgrp eastus2/kubeconfig"

                    kubectl get nodes -owide
                '''
            }
        }

        stage('switch') {
            steps {
                sh '''
                    #!/bin/bash
                    ksctl switch -p azure -n test-e2e-azure -r eastus
                    ksctl switch -p ha-azure -n test-e2e-ha-azure -r eastus2
                '''
            }
        }

        stage('ha-del-nodes') {
            steps {
                sh '''
                    #!/bin/bash
                    sleep 15s
                    ksctl delete ha-azure delete-nodes --noWP 0 -n test-e2e-ha-azure -r eastus2 --approve

                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/azure/ha/test-e2e-ha-azure test-e2e-ha-azure-ksctl-ha-resgrp eastus2/kubeconfig"
                    kubectl get nodes -owide
                    cd /var/lib/jenkins/.ksctl/config/azure/ha/test-e2e-ha-azure\\ test-e2e-ha-azure-ksctl-ha-resgrp\\ eastus2

                    jq . cloud-state.json
                    jq . k8s-state.json
                '''
            }
        }

        stage('ha-add-nodes') {
            steps {
                sh '''
                    #!/bin/bash
                    sleep 1m
                    ksctl create ha-azure add-nodes --noWP 1 -n test-e2e-ha-azure -r eastus2 --approve

                    export KUBECONFIG="/var/lib/jenkins/.ksctl/config/azure/ha/test-e2e-ha-azure test-e2e-ha-azure-ksctl-ha-resgrp eastus2/kubeconfig"
                    kubectl get nodes -owide
                    cd /var/lib/jenkins/.ksctl/config/azure/ha/test-e2e-ha-azure\\ test-e2e-ha-azure-ksctl-ha-resgrp\\ eastus2

                    jq . cloud-state.json
                    jq . k8s-state.json
                '''
            }
        }
    }

    post {
        always {
            sh '''
                #!/bin/bash
                ksctl delete azure -n test-e2e-azure -r eastus --approve -v
                ksctl delete ha-azure -n test-e2e-ha-azure -r eastus2 --approve -v
            '''
        }
    }
}
