name: CI-CD for ksctl main branch

on:
  workflow_dispatch:
  push:
    paths:
      - "pkg/**"
      - "go.mod"
      - "go.sum"
      - "build/**"
      - "test/e2e/**"
      - "test/gh-runner/**"
      - ".github/workflows/e2e-*"
      - ".github/workflows/testing-*"
      - ".github/workflows/ci-main.yaml"
    branches: [main]

concurrency:
  cancel-in-progress: false
  group: ci-e2e-main

jobs:
  # trigger-oci-artifact-build-push:
  #   uses: ./.github/workflows/docker.yaml
  #   secrets: inherit
  #   with:
  #     image_tag: main
  #   permissions:
  #     packages: write
  #     contents: read

  trigger-e2e:
    uses: ./.github/workflows/e2e.yml
    secrets: inherit
