
name: Build and Push of Docker images
on:
  push:
    paths:
    - 'api/**'
    - 'containers/**'
    - 'httpserver/**'
    branches: [ main ]

jobs:
  ksctl_scaler_http:
    runs-on: ubuntu-latest

    env:
      DOCKER_SECRET: ${{ secrets.DOCKER_PASS }}
      HTTPSERVER: docker.io/kubesimplify/ksctl:slim-v1

    steps:
    - uses: actions/checkout@v3

    - name: Install Cosign
      uses: sigstore/cosign-installer@main

    - name: Build the Docker image
      run: docker build --file containers/httpserver_slim/Dockerfile --tag $HTTPSERVER .

    - name: login
      run: docker login -u kubesimplify -p "$DOCKER_SECRET"

    - name: Push to Docker
      run: docker push $HTTPSERVER

    # enable cosign signing
