name: e2e for azure

on:
  workflow_dispatch:
  workflow_call:

jobs:
  execute:
    environment: e2e
    env:
      KUBECONFIG: ${{ vars.KUBECONFIG_KSCTL_LOC }}
      PS4: '+\[\033[0;33m\](\[\033[0;36m\]${BASH_SOURCE##*/}:${LINENO}\[\033[0;33m\])\[\033[0m\] '
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    runs-on: e2e
    defaults:
      run:
        working-directory: test/e2e

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            paths:
              - 'internal/cloudproviders/azure/*'
              - 'internal/k8sdistros/k3s/*'
              - 'internal/k8sdistros/kubeadm/*'
              - 'internal/k8sdistros/*'
              - 'internal/storage/**'
              - 'pkg/helpers/**'
              - 'pkg/logger/**'
              - 'test/e2e/**'
              - 'go.mod'
              - 'go.sum'
              - 'pkg/controllers/**'
              - 'pkg/resources/**'
              - '.github/workflows/e2e-azure.yml'

      - name: create (managed)
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          go run . -op create -file azure/create.json
          go run . -op get -file azure/get.json

      - name: create (k3s ha)
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          go run . -op create -file azure/create-ha.json
          go run . -op get -file azure/get.json

      - name: create (kubeadm ha)
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          go run . -op create -file azure/create-ha-kubeadm.json
          go run . -op get -file azure/get.json

      - name: switch
        if: steps.changes.outputs.paths == 'true'
        run: |
          echo -e "\033[1;34m@@@\033[0m \033[1;35mManaged Cluster\033[0m \033[1;34m@@@\033[0m"

          go run . -op switch -file azure/switch.json

          tree ~/.ksctl/state

          jq -r . ~/.ksctl/state/azure/managed/test-e2e-azure\ eastus/state.json

          sleep 5s

          kubectl get nodes -owide

          echo -e "\033[1;34m@@@\033[0m \033[1;35mHA Cluster (K3s)\033[0m \033[1;34m@@@\033[0m"

          go run . -op switch -file azure/switch-ha.json

          tree ~/.ksctl/state

          jq -r . ~/.ksctl/state/azure/ha/test-e2e-ha-azure\ eastus2/state.json

          sleep 5s

          kubectl get nodes -owide

          echo -e "\033[1;34m@@@\033[0m \033[1;35mHA Cluster (kubeadm)\033[0m \033[1;34m@@@\033[0m"

          go run . -op switch -file azure/switch-ha-kubeadm.json

          tree ~/.ksctl/state

          jq -r . ~/.ksctl/state/azure/ha/test-e2e-kubeadm-ha-azure\ centralindia/state.json

          sleep 5s

          kubectl get nodes -owide

      - name: scaledown kubeadm
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          go run . -op switch -file azure/switch-ha-kubeadm.json

          sleep 30s
          go run . -op scaledown -file azure/scaledown-ha-kubeadm.json

          kubectl get nodes -owide
          jq -r . ~/.ksctl/state/azure/ha/test-e2e-kubeadm-ha-azure\ centralindia/state.json

      - name: scaleup kubeadm
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          go run . -op switch -file azure/switch-ha-kubeadm.json

          sleep 1m
          go run . -op scaleup -file azure/scaleup-ha-kubeadm.json

          kubectl get nodes -owide

          jq -r . ~/.ksctl/state/azure/ha/test-e2e-kubeadm-ha-azure\ centralindia/state.json

      - name: scaledown k3
        if: steps.changes.outputs.paths == 'true'
        run: |

          set -xe
          go run . -op switch -file azure/switch-ha.json

          sleep 30s
          go run . -op scaledown -file azure/scaledown-ha.json

          kubectl get nodes -owide
          jq -r . ~/.ksctl/state/azure/ha/test-e2e-ha-azure\ eastus2/state.json

      - name: scaleup k3
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe

          go run . -op switch -file azure/switch-ha.json

          sleep 30s
          go run . -op scaleup -file azure/scaleup-ha.json

          kubectl get nodes -owide
          jq -r . ~/.ksctl/state/azure/ha/test-e2e-ha-azure\ eastus2/state.json

      - name: delete (managed)
        if: always() && steps.changes.outputs.paths == 'true'
        run: |
          set -xe

          go run . -op delete -file azure/delete.json

      - name: delete (ha k3s)
        if: always() && steps.changes.outputs.paths == 'true'
        run: |
          set -xe

          go run . -op delete -file azure/delete-ha.json

      - name: delete (ha kubeadm)
        if: always() && steps.changes.outputs.paths == 'true'
        run: |
          set -xe

          go run . -op delete -file azure/delete-ha-kubeadm.json
