name: e2e for azure

on:
  workflow_dispatch:
  workflow_call:

jobs:
  execute-aws:
    environment: e2e
    env:
      E2E_FLAGS: debug
      KUBECONFIG: ${{ vars.KUBECONFIG_KSCTL_LOC }}
      PS4: '+\[\033[0;33m\](\[\033[0;36m\]${BASH_SOURCE##*/}:${LINENO}\[\033[0;33m\])\[\033[0m\] '
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: e2e
    defaults:
      run:
        working-directory: test/e2e

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            paths:
              - 'test/gh-runner/**'
              - 'test/e2e/*'
              - 'test/e2e/aws/*'
              - 'go.mod'
              - 'go.sum'
              - '.github/workflows/e2e-aws.yml'
              - 'pkg/**'
              - '!pkg/provider/azure/**'
              - '!pkg/provider/local/**'
              - '!**/*.md'
              - '!**/*.json'
              - '!**/*.yaml'
              - '!.dockerignore'
              - '!.gitignore'

        # run only if some file in 'src' folder was changed
      - name: create (managed)
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          ksctl-e2e-amd64 -op create -file aws/create.json
          ksctl-e2e-amd64 -op info -file aws/info.json

      - name: switch aws eks
        if: steps.changes.outputs.paths == 'true'
        run: |
          echo -e "\033[1;34m@@@\033[0m \033[1;35mManaged Cluster\033[0m \033[1;34m@@@\033[0m"
          ksctl-e2e-amd64 -op switch -file aws/switch.json
          tree ~/.ksctl/state
          jq -r . ~/.ksctl/state/aws/managed/test-e2e-aws\ eu-central-1/state.json
          sleep 5s
          kubectl get nodes -owide

      - name: create (k3s selfmanaged)
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          ksctl-e2e-amd64 -op create -file aws/create-ha.json
          ksctl-e2e-amd64 -op info -file aws/info-ha.json

      - name: create (kubeadm selfmanaged)
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          ksctl-e2e-amd64 -op create -file aws/create-ha-kubeadm.json
          ksctl-e2e-amd64 -op info -file aws/info-ha-kubeadm.json

      - name: get
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          ksctl-e2e-amd64 -op get -file aws/get.json

      - name: switch self managed cluster
        if: steps.changes.outputs.paths == 'true'
        run: |
          echo -e "\033[1;34m@@@\033[0m \033[1;35mselfmanaged Cluster (K3s)\033[0m \033[1;34m@@@\033[0m"
          ksctl-e2e-amd64 -op switch -file aws/switch-ha.json
          tree ~/.ksctl/state
          jq -r . ~/.ksctl/state/aws/selfmanaged/test-e2e-selfmanaged-aws\ ap-south-1/state.json
          sleep 5s
          kubectl get nodes -owide

          echo -e "\033[1;34m@@@\033[0m \033[1;35mselfmanaged Cluster (kubeadm)\033[0m \033[1;34m@@@\033[0m"
          ksctl-e2e-amd64 -op switch -file aws/switch-ha-kubeadm.json
          tree ~/.ksctl/state
          jq -r . ~/.ksctl/state/aws/selfmanaged/test-e2e-kubeadm-selfmanaged-aws\ us-east-1/state.json
          sleep 5s
          kubectl get nodes -owide

      - name: scaledown kubeadm
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          ksctl-e2e-amd64 -op switch -file aws/switch-ha-kubeadm.json

          sleep 30s
          ksctl-e2e-amd64 -op scaledown -file aws/scaledown-ha-kubeadm.json

          kubectl get nodes -owide
          jq -r . ~/.ksctl/state/aws/selfmanaged/test-e2e-kubeadm-selfmanaged-aws\ us-east-1/state.json

      - name: scaleup kubeadm
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          ksctl-e2e-amd64 -op switch -file aws/switch-ha-kubeadm.json

          sleep 1m
          ksctl-e2e-amd64 -op scaleup -file aws/scaleup-ha-kubeadm.json

          kubectl get nodes -owide
          jq -r . ~/.ksctl/state/aws/selfmanaged/test-e2e-kubeadm-selfmanaged-aws\ us-east-1/state.json

      - name: scaledown k3
        if: steps.changes.outputs.paths == 'true'
        run: |

          set -xe
          ksctl-e2e-amd64 -op switch -file aws/switch-ha.json

          sleep 30s
          ksctl-e2e-amd64 -op scaledown -file aws/scaledown-ha.json

          kubectl get nodes -owide
          jq -r . ~/.ksctl/state/aws/selfmanaged/test-e2e-selfmanaged-aws\ ap-south-1/state.json

      - name: scaleup k3
        if: steps.changes.outputs.paths == 'true'
        run: |
          set -xe

          ksctl-e2e-amd64 -op switch -file aws/switch-ha.json

          sleep 30s
          ksctl-e2e-amd64 -op scaleup -file aws/scaleup-ha.json

          kubectl get nodes -owide
          jq -r . ~/.ksctl/state/aws/selfmanaged/test-e2e-selfmanaged-aws\ ap-south-1/state.json

      - name: delete (managed)
        if: always() && steps.changes.outputs.paths == 'true'
        run: |
          set -xe
          ksctl-e2e-amd64 -op delete -file aws/delete.json

      - name: delete (selfmanaged k3s)
        if: always() && steps.changes.outputs.paths == 'true'
        run: |
          set -xe

          ksctl-e2e-amd64 -op delete -file aws/delete-ha.json

      - name: delete (selfmanaged kubeadm)
        if: always() && steps.changes.outputs.paths == 'true'
        run: |
          set -xe

          ksctl-e2e-amd64 -op delete -file aws/delete-ha-kubeadm.json
