name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for submitting your first issue in ksctl. We hope that the maintainers will review your request soon."
        pr-message: "Thank you for submitting your first pull request in ksctl. I am excited for the day when your changes get merged."
