name: Mock-Integration Test

on:
  pull_request:
    paths:
      - 'internal/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
    types: [ labeled ]
  push:
    paths:
    - 'internal/**'
    - 'pkg/**'
    - 'go.mod'
    - 'go.sum'
    branches: [ main ]

jobs:
  build_linux:
    if: ${{ github.event.label.name == 'pr/lgtm' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.0'
      - name: Mock integration testing
        run: |
           cd test/
           go test -bench=. -benchtime=1x -cover -v

  build_macos:
    if: ${{ github.event.label.name == 'pr/lgtm' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.0'
      - name: Mock integration testing
        run: |
           cd test/
           go test -bench=. -benchtime=1x -cover -v

  build_windows:
    if: ${{ github.event.label.name == 'pr/lgtm' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.0'
      - name: Mock integration testing
        run: |
           cd test
           go test -bench=. -benchtime=1x -cover -v


