name: release-on-tag-push

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: goreleaser
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: get the artifacts
        env:
          TAG_NAME: ${{github.ref_name}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --fail-with-body -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/ksctl/ksctl/releases \
          -d "{\"tag_name\":\"${TAG_NAME}\",\"draft\":false,\"prerelease\":false,\"generate_release_notes\":true}"
