name: Regression Test Civo
on:
  push:
    paths:
      - 'internal/cloudproviders/civo/**'
      - 'internal/storage/**'
      - 'pkg/helpers/**'
      - 'pkg/logger/**'
      - 'go.mod'
      - 'go.sum'
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
    paths:
    - 'internal/cloudproviders/civo/**'
    - 'internal/storage/**'
    - 'pkg/helpers/**'
    - 'pkg/logger/**'
    - 'go.mod'
    - 'go.sum'

jobs:
  unit-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    if: |
      (
        github.event.label.name == 'tests/enable' ||
        contains(github.event.pull_request.labels.*.name, 'tests/enable')
      ) &&
      (
        contains(github.event.pull_request.labels.*.name, 'pr/lgtm') != true ||
        github.event.label.name != 'pr/lgtm'
      )

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Testing
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          make unit_test_civo

      - name: Testing
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: scripts
        run: .\test-civo.ps1

  mock-integration-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    if: |
      (
        github.event.label.name == 'tests/enable' ||
        contains(github.event.pull_request.labels.*.name, 'tests/enable')
      ) &&
      (
        contains(github.event.pull_request.labels.*.name, 'pr/lgtm') ||
        github.event.label.name == 'pr/lgtm'
      )
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: integration testing
        working-directory: test
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          go test -bench=BenchmarkCivoTestingManaged -benchtime=1x -cover -v
          go test -bench=BenchmarkCivoTestingHA -benchtime=1x -cover -v

      - name: integration testing
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          make mock_civo_managed
          make mock_civo_ha

