name: Regression Test Logger
on:
  push:
    paths:
      - 'pkg/logger/**'
      - 'go.mod'
      - 'go.sum'
    branches: [ main ]
  pull_request:
    paths:
      - 'pkg/logger/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Unit Test
        run: |
          cd scripts
          chmod u+x test-logger.sh
          ./test-logger.sh

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Unit Test
        run: |
          cd scripts
          .\test-logger.ps1

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Unit Test
        run: |
          cd scripts
          chmod u+x test-logger.sh
          ./test-logger.sh
