name: Regression Test Aws
on:
  push:
    paths:
      - "internal/cloudproviders/aws/**"
      - "internal/storage/**"
      - "pkg/helpers/**"
      - "pkg/logger/**"
      - "go.mod"
      - "go.sum"
    branches: [main]
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    paths:
      - "internal/cloudproviders/aws/**"
      - "internal/storage/**"
      - "pkg/helpers/**"
      - "pkg/logger/**"
      - "go.mod"
      - "go.sum"

jobs:
  unit-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    if: |
      (
        github.event.label.name == 'tests/enable' ||
        contains(github.event.pull_request.labels.*.name, 'tests/enable')
      ) &&
      (
        contains(github.event.pull_request.labels.*.name, 'pr/lgtm') != true ||
        github.event.label.name != 'pr/lgtm'
      )

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Testing
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          make unit_test_aws

      - name: Testing
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: scripts
        run: .\test-aws.ps1

  mock-integration-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    if: |
      (
        github.event.label.name == 'tests/enable' ||
        contains(github.event.pull_request.labels.*.name, 'tests/enable')
      ) &&
      (
        contains(github.event.pull_request.labels.*.name, 'pr/lgtm') ||
        github.event.label.name == 'pr/lgtm'
      )
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: integration testing
        working-directory: test
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          go test -tags testing_aws -bench=BenchmarkAwsTestingManaged -benchtime=1x -cover -v
          go test -tags testing_aws -bench=BenchmarkAwsTestingHA -benchtime=1x -cover -v

      - name: integration testing
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          make mock_aws_managed
          make mock_aws_ha
