name: Regression Test Logger
on:
  push:
    paths:
      - 'pkg/logger/**'
      - 'go.mod'
      - 'go.sum'
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]
    paths:
      - 'pkg/logger/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  unit-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    if: |
      (
        github.event.label.name == 'tests/enable' ||
        contains(github.event.pull_request.labels.*.name, 'tests/enable')
      )

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Testing
        if: ${{ matrix.os != 'windows-latest' }}
        working-directory: scripts
        run: |
          chmod u+x test-logger.sh
          ./test-logger.sh

      - name: Testing
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: scripts
        run: .\test-logger.ps1
